/* eslint-disable */

export type ClassType<T extends abstract new (...args: any) => any> =
  & { new(...args: ConstructorParameters<T>): InstanceType<T> }
  & { [K in keyof T]: T[K] };

/* auto-generated by NAPI-RS */

/**
 * Build the three classes and hand the constructors to JS. Idempotent via
 * the registry; the returned constructors are the same objects on repeat
 * calls.
 */
export declare function buildInheritTestClasses(): object

export declare function makeGenSource(): object

/**
 * Build an `InheritLeaf` instance from a Rust-side data chain, bypassing
 * the JS `new` path entirely.
 */
export declare function makeInheritLeafFromChain(): object

/**
 * Build an `InheritLeaf` from a Rust-side data chain, bypassing the JS
 * `new` path. Distinct Rust/js name from the manual chain's
 * `makeInheritLeafFromChain`.
 */
export declare function makeProcLeafFromChain(): object
export declare class GenSourceClass {
  constructor(label: string)
  push(v: number): void
  [Symbol.iterator](): IterableIterator<number>
  [Symbol.asyncIterator](): AsyncIterableIterator<number>
}

export declare class InheritBaseClass {
  baseValue: number
  renamedProp: number
  constructor(baseValue: number)
  baseGreet(): string
  static bumpBase(that: object, delta: number): number
  /**
   * Static accessor pair on `InheritBase.counter`, backed by a Rust
   * atomic (there is no instance slot for static state).
   */
  get counter(): number
  set counter(v: number)
  /**
   * Result-returning instance accessor pair: reads/writes the base slot
   * and fails loudly on a zero value.
   */
  get checkedValue(): number
  set checkedValue(v: number)
  /** Result-returning static accessor pair over the shared counter. */
  get checkedCounter(): number
  set checkedCounter(v: number)
  /**
   * Result-returning `&self` method (with_own outer + `?`): errors when
   * the base value is zero.
   */
  guardedGreet(): string
  /** Result-returning `this`-injected method. */
  static guard(that: object, v: number): string
  /** Result-returning static method. */
  static staticGuard(v: number): number
  /**
   * Explicit `#[layer(this)]`: no receiver, the instance is injected
   * anyway, so the body reaches the layer slot on its own.
   */
  thisInjected(): string
}

export declare class InheritLeafClass extends InheritMid {
  readonly leafValue: number
  readonly midSeenAfterSuper: number
  constructor(baseValue: number, midValue: number, leafValue: number)
  static leafShout(that: object): string
  static leafConst(): number
}

export declare class InheritMidClass extends InheritBase {
  readonly midValue: number
  readonly baseSeenAfterSuper: number
  constructor(baseValue: number, midValue: number)
  static midDescribe(that: object): string
}

export type GenSource =
  InstanceType<typeof GenSourceClass>;

export declare const GenSource: ClassType<typeof GenSourceClass>;

export type InheritBase =
  InstanceType<typeof InheritBaseClass>;

export declare const InheritBase: ClassType<typeof InheritBaseClass>;

export type InheritLeaf =
  InstanceType<typeof InheritLeafClass>;

export declare const InheritLeaf: ClassType<typeof InheritLeafClass>;

export type InheritMid =
  InstanceType<typeof InheritMidClass>;

export declare const InheritMid: ClassType<typeof InheritMidClass>;
