/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BlitzApp {
  static create(): BlitzApp
  openWindow(document: Document): void
  pumpAppEvents(millis: number): PumpResult
}

export declare class Document {
  constructor(initConfig?: DocumentInitConfig | undefined | null)
  loadHtml(html: string): void
  resolve(currentTimeForAnimations: number): void
  getNode(id: number): Node | null
  deepCloneNode(node: Node): Node
  createElement2(name: string, namespace: string | undefined | null, attrs: Record<string, string>): Node
  createElement(name: string, namespace: string | undefined | null, attrs: Array<Attribute>): Node
  createTextNode(text: string): Node
  createCommentNode(): Node
  createCommentNodeWithContent(content: string): Node
  insert(node?: Node | undefined | null, parent?: Node | undefined | null, anchor?: Node | undefined | null): void
  nextSibling(node: Node): Node | null
  previousSibling(node: Node): Node | null
  parentNode(node: Node): Node | null
  patchProp(node: Node, name: string, value: string, namespace?: string | undefined | null): void
  setStyleProperty(node: Node, name: string, value: string): void
  removeStyleProperty(node: Node, name: string): void
  querySelector(selector: string): Node | null
  remove(node: Node): void
  setElementText(node: Node, text: string): void
  setText(node: Node, text: string): void
}

export declare class Node {
  printTree(level?: number | undefined | null): void
  selfProp(name: string, value: object): void
  addEventListener(eventType: string, handler: () => void): void
  removeEventListener(eventType: string, handler: () => void): void
}

export declare class PumpResult {
  continue: boolean
  exit: boolean
  code?: number
}

export interface Attribute {
  name: string
  value: string
}

export interface DocumentInitConfig {
  uaStylesheets?: Array<string>
  baseHtml?: string
}
