//! One `#[layer(...)]`-annotated impl member and its two expansion faces:
//! the runtime registration inside `define_members` and the TS type-def
//! entry. A member carries its signature, its parsed flags, and knows how
//! to quote itself for both outputs — nothing else needs its internals.

use crate::attrs::{MemberInfo, MemberKind};
use crate::registry::resolve_js_name;
use crate::util::{setter_js_name, to_camel, type_last_ident};
use napi_derive_backend::{FnKind, FnSelf, NapiFn, NapiFnArg, NapiFnArgKind};
use proc_macro2::{Ident, TokenStream as TokenStream2};
use quote::{format_ident, quote};
use syn::{FnArg, GenericArgument, PathArguments, ReturnType, Type};

pub(crate) struct Member {
    pub kind: MemberKind,
    /// `#[layer(this)]` — the instance may be injected without a receiver.
    pub this_injectable: bool,
    /// `#[layer(getter, js_name = "...")]` — explicit JS member name.
    pub js_name: Option<String>,
    /// `#[layer(ts_return_type = "...")]` — explicit TS return type.
    pub ts_return_type: Option<String>,
    pub f: syn::ImplItemFn,
}

impl Member {
    /// Parse the member's `#[layer(...)]` attribute (stripping it from the
    /// item so it passes through cleanly) and wrap the item.
    pub fn parse(f: &mut syn::ImplItemFn) -> Option<Self> {
        let info = MemberInfo::parse(&mut f.attrs)?;
        Some(Self {
            kind: info.kind,
            this_injectable: info.this_injectable,
            js_name: info.js_name,
            ts_return_type: info.ts_return_type,
            f: f.clone(),
        })
    }

    /// The member's `define_members` call. Instance members read their layer
    /// data through `with_own`; static members (no receiver) call the
    /// implementation directly. Everything here lands in
    /// `LayerMembers::define_members` - the `LayerAccessors` side is
    /// generated by the struct block alone.
    pub fn runtime_tokens(&self, self_ty: &Ident) -> TokenStream2 {
        let Self {
            kind,
            this_injectable,
            js_name,
            ts_return_type: _,
            f,
        } = self;
        let name = f.sig.ident.clone();
        let js = js_name
            .clone()
            .unwrap_or_else(|| to_camel(&name.to_string()));
        // Split the signature into JS args and the injected receiver. A
        // parameter named `this` of type `Object` is filled by the runtime
        // with the instance object, so the body can reach any layer's own
        // slot through `with_own`/`with_own_mut` (the current layer's data
        // is already handed to the method as `&self`). `this` never
        // participates in the JS args.
        //
        // `this` is only injectable on an instance member: with a `&self`
        // receiver, or without a receiver when the member is explicitly
        // marked `#[layer(this)]`. A receiver-less member that declares a
        // `this` parameter without the flag is a static method bug, so it is
        // rejected here instead of surfacing as a stray JS argument.
        //
        // A parameter named `env` of type `&Env` is filled by the runtime
        // with the current napi environment, so a getter/method can create
        // JS values or call back into JS without a global env. It also never
        // participates in the JS args.
        let has_receiver = f.sig.receiver().is_some();
        let mut normal: Vec<(usize, Type)> = vec![];
        let mut call: Vec<TokenStream2> = vec![];
        let mut has_this = false;
        let mut has_env = false;
        for a in &f.sig.inputs {
            let FnArg::Typed(pat) = a else { continue };
            let is_named_this = matches!(&*pat.pat, syn::Pat::Ident(pi) if pi.ident == "this")
                && type_last_ident(&pat.ty)
                    .map(|i| i == "Object")
                    .unwrap_or(false);
            if is_named_this && !has_receiver && !this_injectable {
                return syn::Error::new_spanned(
                    a,
                    "a static #[layer] method cannot take a parameter named `this`: \
                     add a `&self` receiver for self + instance injection, or mark \
                     the member with #[layer(this)] for instance injection without a receiver",
                )
                .into_compile_error();
            }
            let is_this = (has_receiver || *this_injectable) && is_named_this;
            let is_env = matches!(&*pat.pat, syn::Pat::Ident(pi) if pi.ident == "env")
                && type_last_ident(&pat.ty)
                    .map(|i| i == "Env")
                    .unwrap_or(false);
            if is_this {
                has_this = true;
                call.push(quote! { &this });
            } else if is_env {
                has_env = true;
                // The closure param `env` is an `Env` value; user methods
                // declare `env: &Env`, so hand over a reference.
                call.push(quote! { &env });
            } else {
                let i = normal.len();
                normal.push((i, (*pat.ty).clone()));
                let bind = format_ident!("a{}", i);
                call.push(quote! { #bind });
            }
        }
        let arg_binds = normal
            .iter()
            .map(|(i, ty)| {
                let bind = format_ident!("a{}", i);
                let is_option = type_last_ident(ty).map(|i| i == "Option").unwrap_or(false);
                if is_option {
                    quote! {
                        let #bind: #ty = if #i < ctx.length() {
                            ctx.get(#i)?
                        } else {
                            None
                        };
                    }
                } else {
                    quote! { let #bind: #ty = ctx.get(#i)?; }
                }
            })
            .collect::<Vec<_>>();

        let ret_is_result = match &f.sig.output {
            ReturnType::Type(_, ty) => type_last_ident(ty).map(|i| i == "Result").unwrap_or(false),
            ReturnType::Default => false,
        };
        let result_tail = if ret_is_result {
            quote! { ? }
        } else {
            quote! {}
        };

        match kind {
            MemberKind::Generator => {
                quote! {
                    napi_helpers::inherits::define_generator(env, proto, "iterator", |env, this, index| {
                        napi_helpers::inherits::with_own::<#self_ty, _>(&this, |d| #self_ty::#name(d, index))#result_tail
                    })?;
                }
            }
            MemberKind::AsyncGenerator => {
                quote! {
                    napi_helpers::inherits::define_generator(env, proto, "asyncIterator", |env, this, index| {
                        napi_helpers::inherits::with_own::<#self_ty, _>(&this, |d| #self_ty::#name(d, index))#result_tail
                    })?;
                }
            }
            MemberKind::Getter => {
                if has_receiver {
                    quote! {
                        napi_helpers::inherits::define_getter(proto, #js, |env, this| {
                            napi_helpers::inherits::with_own::<#self_ty, _>(&this, |d| #self_ty::#name(d, #(#call),*))#result_tail
                        })?;
                    }
                } else if *this_injectable {
                    quote! {
                        napi_helpers::inherits::define_getter(proto, #js, |env, this| {
                            #self_ty::#name(#(#call),*)
                        })?;
                    }
                } else {
                    let static_call = if ret_is_result {
                        quote! { #self_ty::#name(#(#call),*) }
                    } else {
                        quote! { Ok(#self_ty::#name(#(#call),*)) }
                    };
                    quote! {
                        napi_helpers::inherits::define_static_getter(ctor, #js, |env| {
                            #static_call
                        })?;
                    }
                }
            }
            MemberKind::Setter => {
                let js = js_name.clone().unwrap_or_else(|| setter_js_name(&name));
                let Some(value_ty) = normal.first().map(|(_, ty)| ty.clone()) else {
                    return syn::Error::new_spanned(
                        f,
                        "a #[layer(setter)] method needs exactly one value parameter",
                    )
                    .into_compile_error();
                };
                let env_arg = if has_env {
                    quote! { &env, }
                } else {
                    quote! {}
                };
                if has_receiver {
                    quote! {
                        napi_helpers::inherits::define_setter(proto, #js, |env, this, value: #value_ty| {
                            napi_helpers::inherits::with_own_mut::<#self_ty, _>(&this, |d| #self_ty::#name(d, #env_arg value))#result_tail
                        })?;
                    }
                } else if *this_injectable {
                    let this_arg = if has_this {
                        quote! { &this, }
                    } else {
                        quote! {}
                    };
                    let call = if ret_is_result {
                        quote! { #self_ty::#name(#this_arg #env_arg value) }
                    } else {
                        quote! { Ok(#self_ty::#name(#this_arg #env_arg value)) }
                    };
                    quote! {
                        napi_helpers::inherits::define_setter(proto, #js, |env, this, value: #value_ty| {
                            #call
                        })?;
                    }
                } else {
                    // A setter's method already returns `Result<()>`; the
                    // static closure returns it as-is (no `?` - that would
                    // unwrap to `()` and break the closure's `Result<()>`
                    // type).
                    let static_call = if ret_is_result {
                        quote! { #self_ty::#name(#env_arg value) }
                    } else {
                        quote! { Ok(#self_ty::#name(#env_arg value)) }
                    };
                    quote! {
                        napi_helpers::inherits::define_static_setter(ctor, #js, |env, value: #value_ty| {
                            #static_call
                        })?;
                    }
                }
            }
            MemberKind::Constructor => unreachable!("constructor handled separately"),
            MemberKind::Method => {
                if !has_receiver && !this_injectable {
                    let static_call = if ret_is_result {
                        quote! { #self_ty::#name(#(#call),*) }
                    } else {
                        quote! { Ok(#self_ty::#name(#(#call),*)) }
                    };
                    quote! {
                        napi_helpers::inherits::define_static_method(env, ctor, #js, |ctx| {
                            let env = *ctx.env;
                            #(#arg_binds)*
                            #static_call
                        })?;
                    }
                } else if has_receiver {
                    let takes_mut = f
                        .sig
                        .receiver()
                        .map(|r| r.mutability.is_some())
                        .unwrap_or(false);
                    let slot = if takes_mut {
                        quote! { napi_helpers::inherits::with_own_mut::<#self_ty, _> }
                    } else {
                        quote! { napi_helpers::inherits::with_own::<#self_ty, _> }
                    };
                    quote! {
                        napi_helpers::inherits::define_method(env, proto, #js, |ctx| {
                            let env = *ctx.env;
                            let this: napi::bindgen_prelude::Object = ctx.this()?;
                            #(#arg_binds)*
                            #slot(&this, |d| #self_ty::#name(d, #(#call),*))#result_tail
                        })?;
                    }
                } else {
                    // `#[layer(this)]` instance method: no receiver, but the
                    // instance object is injected and the body reaches any
                    // layer's slot through `with_own`/`with_own_mut` itself.
                    // No outer borrow, so same-slot mutable access is fine.
                    quote! {
                        napi_helpers::inherits::define_method(env, proto, #js, |ctx| {
                            let env = *ctx.env;
                            let this: napi::bindgen_prelude::Object = ctx.this()?;
                            #(#arg_binds)*
                            #self_ty::#name(#(#call),*)
                        })?;
                    }
                }
            }
        }
    }

    /// The member's TS type-def entry (`NapiFn`).
    pub fn napi_fn(
        &self,
        ts_params: &[(Ident, Box<Type>)],
        parent: &Ident,
        parent_js: &str,
    ) -> NapiFn {
        let Self {
            kind,
            this_injectable,
            js_name,
            ts_return_type,
            f,
        } = self;
        let name = f.sig.ident.clone();
        let args = if *kind == MemberKind::Constructor {
            ts_params
                .iter()
                .map(|(pname, ty)| NapiFnArg {
                    kind: NapiFnArgKind::PatType(Box::new(syn::PatType {
                        attrs: vec![],
                        pat: Box::new(syn::Pat::Ident(syn::PatIdent {
                            attrs: vec![],
                            by_ref: None,
                            mutability: None,
                            ident: pname.clone(),
                            subpat: None,
                        })),
                        colon_token: Default::default(),
                        ty: Box::new(*ty.clone()),
                    })),
                    ts_arg_type: None,
                })
                .collect()
        } else {
            f.sig
                .inputs
                .iter()
                .filter_map(|a| match a {
                    FnArg::Typed(pat) => {
                        // Injected parameters never take part in the JS
                        // arguments, so they stay out of the TS signature too.
                        let is_named_this =
                            matches!(&*pat.pat, syn::Pat::Ident(pi) if pi.ident == "this")
                                && type_last_ident(&pat.ty)
                                    .map(|i| i == "Object")
                                    .unwrap_or(false);
                        let is_injected = (f.sig.receiver().is_some() || *this_injectable)
                            && is_named_this
                            || matches!(&*pat.pat, syn::Pat::Ident(pi) if pi.ident == "env")
                                && type_last_ident(&pat.ty)
                                    .map(|i| i == "Env")
                                    .unwrap_or(false);
                        if is_injected {
                            None
                        } else {
                            Some(NapiFnArg {
                                kind: NapiFnArgKind::PatType(Box::new(pat.clone())),
                                ts_arg_type: None,
                            })
                        }
                    }
                    FnArg::Receiver(_) => None,
                })
                .collect()
        };
        let ret = match &f.sig.output {
            ReturnType::Default => None,
            ReturnType::Type(_, ty) => Some((**ty).clone()),
        };
        // A return type that carries `LayerRef<L>` (possibly inside
        // `Result` / `Option` / `Vec`) is emitted as `L`'s JS class name so
        // the TS defs are precise instead of `Any`; the runtime conversion
        // still runs through the normal `ToNapiValue` impls.
        // A return type that carries `LayerRef<L>` (possibly inside
        // `Result` / `Option` / `Vec`) is emitted as `L`'s JS class name so
        // the TS defs are precise instead of `Any`; the runtime conversion
        // still runs through the normal `ToNapiValue` impls. An explicit
        // `#[layer(ts_return_type = "...")]` takes precedence — the
        // automatic mapping needs the referenced layer's struct block to
        // have been expanded already, which module order does not
        // guarantee.
        let ts_return_type = ts_return_type
            .clone()
            .or_else(|| ret.as_ref().and_then(layer_ts_type));
        // Generator protocol members are driven by the engine: no JS
        // arguments, and the per-step item type wraps into an iterator.
        let ts_return_type = match kind {
            MemberKind::Generator | MemberKind::AsyncGenerator => ret.as_ref().and_then(|r| {
                let item = unwrap_wrapped(r)?;
                let (ts, _) = napi_derive_backend::ty_to_ts_type(item, true, false, false);
                let prefix = if matches!(kind, MemberKind::AsyncGenerator) {
                    "AsyncIterableIterator"
                } else {
                    "IterableIterator"
                };
                Some(format!("{prefix}<{ts}>"))
            }),
            _ => ts_return_type,
        };
        let fallback = match kind {
            MemberKind::Constructor => "constructor".to_owned(),
            MemberKind::Getter => to_camel(&name.to_string()),
            MemberKind::Setter => setter_js_name(&name),
            MemberKind::Method => to_camel(&name.to_string()),
            MemberKind::Generator => "[Symbol.iterator]".to_owned(),
            MemberKind::AsyncGenerator => "[Symbol.asyncIterator]".to_owned(),
        };
        let (kind_, js_name) = (
            match kind {
                MemberKind::Constructor => FnKind::Constructor,
                MemberKind::Getter => FnKind::Getter,
                MemberKind::Setter => FnKind::Setter,
                MemberKind::Method => FnKind::Normal,
                MemberKind::Generator | MemberKind::AsyncGenerator => FnKind::Normal,
            },
            js_name.clone().unwrap_or(fallback),
        );
        // Instance vs static is derived from the signature: `&self`/`&mut
        // self` receiver means an instance member, no receiver means a
        // static one. A `#[layer(this)]` member has no receiver but is still
        // an instance member, so it type-defs as one.
        let fn_self = if let Some(recv) = f.sig.receiver() {
            if recv.reference.is_some() {
                if recv.mutability.is_some() {
                    Some(FnSelf::MutRef)
                } else {
                    Some(FnSelf::Ref)
                }
            } else {
                Some(FnSelf::Value)
            }
        } else if *this_injectable {
            Some(FnSelf::Ref)
        } else {
            None
        };
        NapiFn {
            name,
            js_name,
            module_exports: false,
            attrs: vec![],
            args,
            ret,
            is_ret_result: false,
            is_async: false,
            within_async_runtime: false,
            fn_self,
            kind: kind_,
            vis: f.vis.clone(),
            parent: Some(parent.clone()),
            parent_js_name: Some(parent_js.to_owned()),
            strict: false,
            return_if_invalid: false,
            js_mod: None,
            ts_generic_types: None,
            ts_type: None,
            ts_args_type: match kind {
                MemberKind::Generator | MemberKind::AsyncGenerator => Some(String::new()),
                _ => None,
            },
            ts_return_type,
            skip_typescript: false,
            comments: crate::util::extract_doc(&f.attrs),
            parent_is_generator: false,
            parent_is_async_generator: false,
            writable: false,
            enumerable: false,
            configurable: false,
            catch_unwind: false,
            unsafe_: false,
            register_name: format_ident!("__layer_placeholder"),
            no_export: false,
        }
    }
}

/// The TS signature of a return type, when it carries a `LayerRef<L>`.
/// `LayerRef<L>` maps to `L`'s JS class name (resolved through the layer
/// registry); `Result` / `Option` / `Vec` wrappers map to `L`, `L | null`
/// and `Array<L>` respectively. Any other type yields `None`, leaving the
/// default napi type mapping untouched.
fn layer_ts_type(ty: &Type) -> Option<String> {
    let Type::Path(path) = ty else {
        return None;
    };
    let seg = path.path.segments.last()?;
    let inner_ty = || -> Option<Type> {
        let PathArguments::AngleBracketed(args) = &seg.arguments else {
            return None;
        };
        let GenericArgument::Type(t) = args.args.first()? else {
            return None;
        };
        Some(t.clone())
    };
    match seg.ident.to_string().as_str() {
        "LayerRef" => {
            let Type::Path(inner) = inner_ty()? else {
                return None;
            };
            let name = inner.path.segments.last()?.ident.to_string();
            Some(resolve_js_name(&name))
        }
        "Result" => layer_ts_type(&inner_ty()?),
        "Option" => layer_ts_type(&inner_ty()?).map(|t| format!("{t} | null")),
        "Vec" => layer_ts_type(&inner_ty()?).map(|t| format!("Array<{t}>")),
        _ => None,
    }
}

/// Peel `Result<T>` / `Option<T>` wrappers down to the bare item type.
fn unwrap_wrapped(ty: &Type) -> Option<&Type> {
    let Type::Path(path) = ty else {
        return Some(ty);
    };
    let seg = path.path.segments.last()?;
    if seg.ident != "Option" && seg.ident != "Result" {
        return Some(ty);
    }
    let PathArguments::AngleBracketed(args) = &seg.arguments else {
        return None;
    };
    let GenericArgument::Type(inner) = args.args.first()? else {
        return None;
    };
    unwrap_wrapped(inner)
}
