/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BufferRenderer {
  static create(options: BufferRendererOptions): BufferRenderer
  /**
   * Resize the virtual surface. Dimensions are CSS pixels; the returned
   * frame dimensions are multiplied by `scale`.
   */
  resize(options: BufferRendererOptions): void
  /**
   * Resolve the document and render it into a fresh RGBA8 buffer.
   *
   * This is a deliberately simple first architecture pass: every call paints
   * the whole viewport. Later we can layer dirty-region tracking and buffer
   * reuse on top without changing the separation from the native window path.
   */
  render(doc: DocHandle): BufferFrame
}

/**
 * JS-facing handle. Holds the shared document state and exposes the flat
 * nodeId-based DOM API.
 */
export declare class DocHandle {
  /** Create a new document. */
  static create(config: DocHandleConfig): DocHandle
  /**
   * Recompute style + layout. Called from JS after batches of mutations or
   * before painting. `time_ms` drives CSS animations.
   */
  resolve(timeMs: number): void
  /**
   * Register a font from a raw byte buffer.
   *
   * The buffer must contain a single TTF/OTF/WOFF/WOFF2 font file (or
   * a TrueType collection — every face inside will be registered).
   * Returns the number of faces that were added.
   *
   * This bypasses blitz's `@font-face` machinery entirely: there is
   * no network fetch, no CSS parsing, just a direct insert into the
   * shared `Collection`. The font becomes available to all subsequent
   * layout/paint work driven by this document.
   *
   * The buffer is taken by value and stored inside the font cache;
   * callers may safely drop their reference to it after this call
   * returns.
   */
  registerFont(data: Uint8Array, options?: RegisterFontOptions | undefined | null): number
  /** The id of the root node (always 0 for blitz, but expose it for JS). */
  rootNodeId(): bigint
  /** The id of `<html>` (the root *element*). */
  rootElementId(): bigint
  /**
   * Update the set of node ids JS currently has live wrappers for. Rust
   * uses this to short-circuit dispatch when no listener could exist.
   */
  setListenedNodes(ids: Array<bigint>): void
  /**
   * Add a single node id to the listened set. Cheaper than calling
   * `set_listened_nodes` for incremental subscription updates.
   */
  addListenedNode(id: bigint): void
  /** Remove a node id from the listened set. */
  removeListenedNode(id: bigint): void
  /**
   * Replace document content from an HTML string. Useful for tests and
   * initial bootstrapping when `base_html` was not enough.
   */
  loadHtml(html: string): void
  /** Find a single node by CSS selector. Returns its node id or null. */
  querySelector(selector: string): bigint | null
  /** Find all nodes by CSS selector. Returns a list of node ids. */
  querySelectorAll(selector: string): Array<bigint>
  /**
   * Element-scoped `querySelector`: first match in the subtree rooted at
   * `root_id` (exclusive — the root element itself is not a candidate,
   * matching the DOM spec for `Element.querySelector`). We parse the
   * selector via blitz's public `try_parse_selector_list` and then call
   * stylo's `dom_apis::query_selector` directly with `root_id`'s node as
   * the root — bypassing blitz's `query_selector_raw`, which is hardcoded
   * to `self.root_node()`.
   */
  querySelectorIn(rootId: bigint, selector: string): bigint | null
  /**
   * Element-scoped `querySelectorAll`: all matches in the subtree rooted
   * at `root_id` (exclusive). Same approach as `query_selector_in`.
   */
  querySelectorAllIn(rootId: bigint, selector: string): Array<bigint>
  /** Lookup by `id=` attribute, like `document.getElementById`. */
  getElementById(id: string): bigint | null
  /**
   * Find the document's `<title>` element id, or None if no title
   * element exists in the tree. Uses the same pre-order DFS as the
   * other structural lookups (`html`/`head`/`body`) — cheaper than
   * `querySelector("title")` which dispatches through the CSS
   * selector engine.
   */
  findTitleNodeId(): bigint | null
  /** True iff the given node id currently exists in the document. */
  hasNode(id: bigint): boolean
  /**
   * Create an element node. Returns its node id. The element is detached
   * (no parent) until inserted.
   */
  createElement(localName: string, namespace?: string | undefined | null, attrs?: Array<AttrInit> | undefined | null): bigint
  /** Create a text node with the given content. */
  createTextNode(text: string): bigint
  /** Create an empty comment node. */
  createCommentNode(): bigint
  /** Deep-clone an existing node and return the new node's id. */
  deepCloneNode(nodeId: bigint): bigint
  /**
   * Shallow-clone a node: same data (tag name, attributes, text
   * payload, etc.) but no children. The new node has no parent.
   * Returns the new node's id.
   *
   * Cloning a missing nodeId returns 0 (the document root) — the
   * caller should make sure the source id is valid first. The
   * alternative (returning `Option<u64>`) noisily complicates the
   * JS-side cloneNode wrapper for a case JS code can never trigger.
   */
  shallowCloneNode(nodeId: bigint): bigint
  /** Parent node id, if any. */
  parentId(nodeId: bigint): bigint | null
  /** First child id, if any. */
  firstChildId(nodeId: bigint): bigint | null
  /** Last child id, if any. */
  lastChildId(nodeId: bigint): bigint | null
  /** All children, in document order. */
  childIds(nodeId: bigint): Array<bigint>
  /** Next sibling id, if any. */
  nextSiblingId(nodeId: bigint): bigint | null
  /** Previous sibling id, if any. */
  previousSiblingId(nodeId: bigint): bigint | null
  /** DOM-style `nodeType` (1=Element, 3=Text, 8=Comment, 9=Document). */
  nodeType(nodeId: bigint): number
  /**
   * Local element tag name (lowercased), e.g. "div". Returns None for
   * non-element nodes.
   */
  tagName(nodeId: bigint): string | null
  /**
   * Concatenated text content of this node and its descendants. Mirrors
   * `Node.textContent`.
   */
  textContent(nodeId: bigint): string | null
  /** Get an attribute value, or None if missing or node is not an element. */
  getAttribute(nodeId: bigint, name: string): string | null
  /**
   * All attribute (name, value) pairs on this node, or empty if not an
   * element.
   */
  getAttributes(nodeId: bigint): Array<AttrInit>
  /** Set an attribute on an element. */
  setAttribute(nodeId: bigint, name: string, value: string, namespace?: string | undefined | null): void
  /** Remove an attribute from an element. */
  removeAttribute(nodeId: bigint, name: string, namespace?: string | undefined | null): void
  /** Set a single inline style property (e.g. "color", "#ff0000"). */
  setStyleProperty(nodeId: bigint, name: string, value: string): void
  /** Remove a single inline style property. */
  removeStyleProperty(nodeId: bigint, name: string): void
  /**
   * Read a single inline style property's serialized value, or
   * `null` if the property is not set on this element.
   *
   * Implements CSSOM `CSSStyleDeclaration.getPropertyValue`:
   * the value is rendered through stylo's `property_value_to_css`,
   * which handles both longhands and shorthands. An unknown
   * property name (one stylo doesn't recognize) also returns `null`
   * rather than throwing — matching browser semantics.
   */
  getStyleProperty(nodeId: bigint, name: string): string | null
  /**
   * List the long-hand names of every property currently in this
   * element's inline style block.
   *
   * Used by the JS-side `style` Proxy to implement `Object.keys`,
   * `for...in`, and `length`. The names are stylo's longhand
   * identifiers (e.g. `"color"`, `"margin-top"`). Custom properties
   * (`--foo`) are included as-is.
   */
  getStylePropertyNames(nodeId: bigint): Array<string>
  /**
   * Read the entire `style` attribute as a single CSS string. Used
   * to back `CSSStyleDeclaration.cssText`. Returns the empty string
   * when the element has no inline style at all.
   */
  getStyleAttribute(nodeId: bigint): string
  /**
   * Replace this node's text content. For elements this resets to a single
   * text-node child; for text/comment nodes this updates their content.
   */
  setTextContent(nodeId: bigint, text: string): void
  /** Append `child` as the last child of `parent`. Mirrors `Node.appendChild`. */
  appendChild(parentId: bigint, childId: bigint): void
  /**
   * Insert `node` immediately before `anchor`. If `anchor` is None, behaves
   * like `appendChild`. Matches `Node.insertBefore`.
   */
  insertBefore(parentId: bigint, nodeId: bigint, anchorId?: bigint | undefined | null): void
  /** Insert `node` immediately after `anchor`. */
  insertAfter(anchorId: bigint, nodeId: bigint): void
  /**
   * Detach a node from its parent. The node is kept around (still
   * addressable by id) so JS wrappers stay valid. Use `drop_node` to
   * release storage.
   */
  remove(nodeId: bigint): void
  /** Detach and free the node. */
  dropNode(nodeId: bigint): void
  /** Replace `anchor` with `node` in its parent. */
  replaceWith(anchorId: bigint, nodeId: bigint): void
  /** Replace this element's inner HTML. */
  setInnerHtml(nodeId: bigint, html: string): void
  /**
   * Serialize this node (including the node itself) to HTML. Mirrors
   * `Element.outerHTML`. Returns None for unknown nodes.
   */
  outerHtml(nodeId: bigint): string | null
  /**
   * Serialize the children of this node to HTML, without the node's own
   * open/close tags. Mirrors `Element.innerHTML`.
   */
  innerHtml(nodeId: bigint): string | null
  /**
   * First element id matching the given local tag name (lowercase),
   * or None if no element matches. Pre-order traversal from the
   * document root.
   */
  findFirstByLocalName(name: string): bigint | null
  /**
   * All element ids matching the given local tag name, in tree order.
   * Mirrors `getElementsByTagName(name)` minus the live-collection
   * semantics — JS gets a snapshot.
   */
  findAllByLocalName(name: string): Array<bigint>
  /**
   * All element ids matching the given local tag name, scoped to the
   * subtree rooted at `root_id` (exclusive — `root_id` itself is not
   * checked). Pre-order DFS from `root_id`'s children.
   */
  findAllByLocalNameIn(rootId: bigint, name: string): Array<bigint>
  /**
   * All element ids in the subtree rooted at `root_id` (exclusive),
   * i.e. every descendant element regardless of tag. Backs
   * `element.getElementsByTagName("*")`.
   */
  findAllElementsIn(rootId: bigint): Array<bigint>
  /**
   * All element ids whose `class` attribute contains `class_name` as
   * one of its whitespace-separated tokens. Document-scoped.
   */
  findAllByClassName(className: string): Array<bigint>
  /**
   * All element ids whose `class` attribute contains `class_name`,
   * scoped to the subtree rooted at `root_id` (exclusive).
   */
  findAllByClassNameIn(rootId: bigint, className: string): Array<bigint>
  /**
   * `<html>` element id. Uses the `local_name!` macro for a zero-cost
   * atom comparison. Returns None for documents without an `<html>`
   * root (unusual but possible during partial parsing).
   */
  htmlElementId(): bigint | null
  /** `<head>` element id, or None if missing. */
  headElementId(): bigint | null
  /** `<body>` element id, or None if missing. */
  bodyElementId(): bigint | null
}

/** Plain attribute pair used by the create/insert APIs. */
export interface AttrInit {
  name: string
  value: string
  namespace?: string
}

export interface BufferFrame {
  /** Frame width in physical pixels. */
  width: number
  /** Frame height in physical pixels. */
  height: number
  /** Device scale factor used to render the frame. */
  scale: number
  /** RGBA8 pixels, row-major, 4 bytes per pixel. */
  data: Uint8Array
}

export interface BufferRendererOptions {
  /** Viewport width in CSS pixels. */
  width: number
  /** Viewport height in CSS pixels. */
  height: number
  /** Device scale factor. Defaults to 1.0. */
  scale?: number
}

/** JS reports back per-event how dispatch went. */
export interface DispatchResult {
  /** JS called `event.preventDefault()` somewhere. */
  defaultPrevented: boolean
  /**
   * JS called `event.stopPropagation()` somewhere. We don't need this on the
   * Rust side semantically (JS already stopped its own bubble), but we still
   * surface it so blitz can skip its default action when appropriate.
   */
  propagationStopped: boolean
  /** JS wants a redraw; usually because a listener mutated the DOM. */
  requestRedraw: boolean
}

/** Configuration passed to `DocHandle.create`. */
export interface DocHandleConfig {
  /** Optional UA stylesheets. Defaults to blitz's DEFAULT_CSS. */
  uaStylesheets?: Array<string>
  /** Optional initial HTML. Defaults to a blank document. */
  baseHtml?: string
  /**
   * Required: a JS callback `(payload: EventPayload) => DispatchResult` that
   * the Rust side calls every time blitz produces a DomEvent. The JS layer
   * uses it to drive its own `EventTarget` chain.
   */
  onDispatch: (arg: EventPayload) => DispatchResult
}

/**
 * One DomEvent serialized for JS consumption.
 *
 * `chain` lists node ids from the event target (index 0) up to the root.
 * JS uses this to run capture (root -> target) followed by bubble
 * (target -> root) using a standard `EventTarget` for each node.
 */
export interface EventPayload {
  /** Event name in DOM-spec lowercased form, e.g. "click", "pointerdown". */
  eventType: string
  /** node id of the original event target. */
  target: bigint
  /** node id chain, target first, root last. */
  chain: Array<bigint>
  /** `event.bubbles` */
  bubbles: boolean
  /** `event.cancelable` */
  cancelable: boolean
  /** Pointer/mouse details, when applicable. */
  pointer?: PointerData
  /** Wheel delta, when applicable. */
  wheel?: WheelData
  /** Keyboard details, when applicable. */
  key?: KeyData
  /** `<input>` value carried by `Input` events. */
  input?: InputData
  /** IME details, when applicable. */
  ime?: ImeData
}

export interface ImeData {
  /** "enabled" | "disabled" | "preedit" | "commit" | "deleteSurrounding" */
  kind: string
  text?: string
  cursorStart?: number
  cursorEnd?: number
  beforeBytes?: number
  afterBytes?: number
}

export interface InputData {
  value: string
}

export interface KeyData {
  /** e.g. "a", "ArrowLeft", "Enter" */
  key: string
  /** e.g. "KeyA", "ArrowLeft", "Enter" */
  code: string
  location: number
  modsBits: number
  repeat: boolean
  isComposing: boolean
  /** "pressed" | "released" */
  state: string
  text?: string
}

export interface PointerData {
  /** "mouse" | "pen" | "finger" */
  kind: string
  /** Pointer id; for mouse / pen this is 1, for finger it's the finger id. */
  pointerId: number
  isPrimary: boolean
  pageX: number
  pageY: number
  clientX: number
  clientY: number
  screenX: number
  screenY: number
  button: number
  buttons: number
  pressure: number
  tiltX: number
  tiltY: number
  twist: number
  modsBits: number
}

/**
 * Options for `DocHandle.registerFont`. All fields are optional and act
 * as overrides for the metadata that `parley` would otherwise read from
 * the font file's own tables.
 *
 * Mirrors the subset of CSS `@font-face` descriptors that map cleanly
 * onto the underlying font cache. Each `weight` / `style` / `stretch`
 * value is a CSS string (e.g. `"400"`, `"bold"`, `"italic"`,
 * `"oblique 14deg"`, `"condensed"`, `"75%"`); invalid input is
 * reported back to JS as a thrown error, matching how the browser
 * rejects invalid `FontFaceDescriptors`.
 */
export interface RegisterFontOptions {
  /**
   * Override the family name reported to CSS. If omitted, the family
   * name embedded in the font file is used.
   */
  familyName?: string
  /**
   * CSS `font-weight` descriptor string, e.g. `"400"`, `"bold"`,
   * `"100 900"` (variable). For variable fonts the lower bound is
   * used as the registered weight.
   */
  weight?: string
  /**
   * CSS `font-style` descriptor, e.g. `"normal"`, `"italic"`,
   * `"oblique"`, `"oblique 14deg"`.
   */
  style?: string
  /**
   * CSS `font-stretch` descriptor, e.g. `"normal"`, `"condensed"`,
   * `"75%"`. (Standard name; we keep the CSS spelling rather than
   * fontique's `width`.)
   */
  stretch?: string
}

export interface WheelData {
  /** "lines" | "pixels" */
  mode: string
  deltaX: number
  deltaY: number
  pageX: number
  pageY: number
  clientX: number
  clientY: number
  buttons: number
  modsBits: number
}
