/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * One DomEvent serialized for JS consumption.
 *
 * Built once per event and passed to the registered JS event factory.
 * Rust drives the capture/target/bubble walk separately.
 */
export declare class EventPayload {
  /** Event name in DOM-spec lowercased form, e.g. "click", "pointerdown". */
  get type(): string
  /** `event.bubbles` */
  get bubbles(): boolean
  /** `event.cancelable` */
  get cancelable(): boolean
  /** Pointer/mouse details, when applicable. */
  get pointer(): PointerData | null
  /** Wheel delta, when applicable. */
  get wheel(): WheelData | null
  /** Keyboard details, when applicable. */
  get key(): KeyData | null
  /** `<input>` value carried by `Input` events. */
  get input(): InputData | null
  /** IME details, when applicable. */
  get ime(): ImeData | null
}

export declare class ImeData {
  /** "enabled" | "disabled" | "preedit" | "commit" | "deleteSurrounding" */
  get kind(): string
  get text(): string | null
  get cursorStart(): number | null
  get cursorEnd(): number | null
  get beforeBytes(): number | null
  get afterBytes(): number | null
}

export declare class InputData {
  get value(): string
}

export declare class InputDataHandle {
  /**
   * Current text value of the input/textarea.
   *
   * If a live `TextInputData` exists (created during layout), returns
   * the editor's text. Otherwise falls back to the `value` attribute.
   */
  get value(): string
  set value(value: string)
  /**
   * Checked state for checkbox/radio inputs.
   *
   * Reads from `CheckboxInput` special data if present, otherwise
   * falls back to the `checked` attribute.
   */
  get checked(): boolean
  set checked(checked: boolean)
  /** Whether this input currently has focus. */
  get focused(): boolean
}

export declare class KeyData {
  /** e.g. "a", "ArrowLeft", "Enter" */
  get key(): string
  /** e.g. "KeyA", "ArrowLeft", "Enter" */
  get code(): string
  get location(): number
  get modsBits(): number
  get repeat(): boolean
  get isComposing(): boolean
  /** "pressed" | "released" */
  get state(): string
  get text(): string | null
}

/** Information about a monitor. Wraps winit's `MonitorHandle`. */
export declare class MonitorInfo {
  get id(): string
  get name(): string | null
  get x(): number
  get y(): number
  get scaleFactor(): number
  get currentVideoMode(): VideoModeInfo | null
  get videoModes(): Array<VideoModeInfo>
}

export declare class NativeApp {
  /** Build the winit event loop. */
  static create(): NativeApp
  /**
   * Install (or replace) the JS callback that receives app/window
   * events. JS wires this in its `BlitzApp` constructor; calling
   * again replaces the previous handler.
   *
   * The callback receives an `AppEventPayload` and must return an
   * `AppDispatchResult` reporting whether the JS-side `Event` had
   * `preventDefault()` called on it.
   */
  setAppEventHandler(callback: (arg: AppEventPayload) => AppDispatchResult): void
  /**
   * Attach a new window to the given document handle. The same handle can
   * only be attached to one window. The JS DocHandle keeps working after
   * this call (it shares state with the window via Rc<RefCell<...>>), so
   * JS can keep mutating the DOM after `openWindow`.
   *
   * `options` maps directly to a winit `WindowAttributes`. If the document
   * carries a `<title>` element, blitz's mutator-flush will overwrite the
   * title shortly after open; this is expected, with the document treated
   * as the source of truth for window-title content.
   *
   * The returned `Window` carries the winit `WindowId` of the created
   * window, which we use as the napi-side window identifier.
   */
  openWindow(doc: NativeDoc, options?: WindowOptions | undefined | null): NativeWindow
  /**
   * Synchronously close the given window. Removes it from the
   * application's window map (or from our pending queue if it has not
   * been initialised yet). The window stops painting and receiving
   * events as soon as this call returns.
   *
   * This is intentionally not GC-driven: dropping the JS `Window` object
   * does not close the OS window. Callers must invoke this explicitly.
   */
  closeWindow(window: NativeWindow): void
  /**
   * List all available monitors with full metadata. Returns `[]` if
   * no windows have been created yet.
   */
  availableMonitors(): Array<MonitorInfo>
  /**
   * The primary monitor. Returns `None` if no windows have been
   * created yet.
   */
  primaryMonitor(): MonitorInfo | null
  /** Pump pending winit events for at most `millis` milliseconds. */
  pumpAppEvents(millis: number): PumpResult
  /**
   * Set the document zoom level. `1.0` is unzoomed. Combined with the
   * system scale factor to produce the total viewport scale
   * (`hidpi_scale * zoom`) that scales layout and CSS transforms.
   */
  setZoom(window: NativeWindow, zoom: number): void
  /** Get the current document zoom level. */
  getZoom(window: NativeWindow): number
}

export declare class NativeDoc {
  static create(config: DocHandleConfig): NativeDoc
  resolve(timeMs: number): void
  registerFont(data: Uint8Array, options?: RegisterFontOptions | undefined | null): number
  rootNodeId(): bigint
  rootElementId(): bigint
  setDocumentRef(document: object): void
  /**
   * Store a ref to the JS Window object so Rust can forward
   * pointer events to it via the registered dispatch function.
   */
  setWindowRef(window: object): void
  /**
   * Replace document content from an HTML string. Useful for tests and
   * initial bootstrapping when `base_html` was not enough.
   */
  loadHtml(html: string): void
  /** Find a single node by CSS selector. Returns a wrapped JS Node or null. */
  querySelector(selector: string): object | null
  /** Find all nodes by CSS selector. Returns wrapped JS Node objects. */
  querySelectorAll(selector: string): Array<object>
  /**
   * Element-scoped `querySelector`: first match in the subtree rooted at
   * `root_id` (exclusive — the root element itself is not a candidate,
   * matching the DOM spec for `Element.querySelector`). We parse the
   * selector via blitz's public `try_parse_selector_list` and then call
   * stylo's `dom_apis::query_selector` directly with `root_id`'s node as
   * the root — bypassing blitz's `query_selector_raw`, which is hardcoded
   * to `self.root_node()`.
   */
  querySelectorIn(rootId: bigint, selector: string): bigint | null
  /**
   * Element-scoped `querySelectorAll`: all matches in the subtree rooted
   * at `root_id` (exclusive). Same approach as `query_selector_in`.
   */
  querySelectorAllIn(rootId: bigint, selector: string): Array<bigint>
  /** Lookup by `id=` attribute, like `document.getElementById`. */
  getElementById(id: string): object | null
  /**
   * Find the document's `<title>` element id, or None if no title
   * element exists in the tree. Uses the same pre-order DFS as the
   * other structural lookups (`html`/`head`/`body`) — cheaper than
   * `querySelector("title")` which dispatches through the CSS
   * selector engine.
   */
  findTitleNode(): object | null
  /** True iff the given node id currently exists in the document. */
  hasNode(id: bigint): boolean
  nodeHandle(id: bigint): NativeNode | null
  /**
   * Create an element node. Returns a wrapped JS Node. The element is
   * detached (no parent) until inserted.
   */
  createElement(localName: string, namespace?: string | undefined | null, attrs?: Array<AttrInit> | undefined | null): object
  /** Create a text node with the given content. Returns a wrapped JS Node. */
  createTextNode(text: string): object
  /** Create a comment node with the given content. Returns a wrapped JS Node. */
  createCommentNode(text: string): object
  /** Deep-clone an existing node and return the new node's id. */
  deepCloneNode(nodeId: bigint): bigint
  /**
   * Shallow-clone a node: same data (tag name, attributes, text
   * payload, etc.) but no children. The new node has no parent.
   * Returns the new node's id.
   *
   * Cloning a missing nodeId returns 0 (the document root) — the
   * caller should make sure the source id is valid first. The
   * alternative (returning `Option<u64>`) noisily complicates the
   * JS-side cloneNode wrapper for a case JS code can never trigger.
   */
  shallowCloneNode(nodeId: bigint): bigint
  /** Parent node id, if any. */
  parentId(nodeId: bigint): bigint | null
  /** First child id, if any. */
  firstChildId(nodeId: bigint): bigint | null
  /** Last child id, if any. */
  lastChildId(nodeId: bigint): bigint | null
  /** All children, in document order. */
  childIds(nodeId: bigint): Array<bigint>
  /** Next sibling id, if any. */
  nextSiblingId(nodeId: bigint): bigint | null
  /** Previous sibling id, if any. */
  previousSiblingId(nodeId: bigint): bigint | null
  /** DOM-style `nodeType` (1=Element, 3=Text, 8=Comment, 9=Document). */
  nodeType(nodeId: bigint): number
  /**
   * Local element tag name (lowercased), e.g. "div". Returns None for
   * non-element nodes.
   */
  tagName(nodeId: bigint): string | null
  /**
   * Concatenated text content of this node and its descendants. Mirrors
   * `Node.textContent`.
   */
  textContent(nodeId: bigint): string | null
  /** Get an attribute value, or None if missing or node is not an element. */
  getAttribute(nodeId: bigint, name: string): string | null
  /**
   * All attribute (name, value) pairs on this node, or empty if not an
   * element.
   */
  getAttributes(nodeId: bigint): Array<AttrInit>
  /** Set an attribute on an element. */
  setAttribute(nodeId: bigint, name: string, value: string, namespace?: string | undefined | null): void
  /** Remove an attribute from an element. */
  removeAttribute(nodeId: bigint, name: string, namespace?: string | undefined | null): void
  /** Set a single inline style property (e.g. "color", "#ff0000"). */
  setStyleProperty(nodeId: bigint, name: string, value: string): void
  /** Remove a single inline style property. */
  removeStyleProperty(nodeId: bigint, name: string): void
  /**
   * Read a single inline style property's serialized value, or
   * `null` if the property is not set on this element.
   *
   * Implements CSSOM `CSSStyleDeclaration.getPropertyValue`:
   * the value is rendered through stylo's `property_value_to_css`,
   * which handles both longhands and shorthands. An unknown
   * property name (one stylo doesn't recognize) also returns `null`
   * rather than throwing — matching browser semantics.
   */
  getStyleProperty(nodeId: bigint, name: string): string | null
  /**
   * List the long-hand names of every property currently in this
   * element's inline style block.
   *
   * Used by the JS-side `style` Proxy to implement `Object.keys`,
   * `for...in`, and `length`. The names are stylo's longhand
   * identifiers (e.g. `"color"`, `"margin-top"`). Custom properties
   * (`--foo`) are included as-is.
   */
  getStylePropertyNames(nodeId: bigint): Array<string>
  /**
   * Read the entire `style` attribute as a single CSS string. Used
   * to back `CSSStyleDeclaration.cssText`. Returns the empty string
   * when the element has no inline style at all.
   */
  getStyleAttribute(nodeId: bigint): string
  /**
   * Replace this node's text content. For elements this resets to a single
   * text-node child; for text/comment nodes this updates their content.
   */
  setTextContent(nodeId: bigint, text: string): void
  /** Append `child` as the last child of `parent`. Mirrors `Node.appendChild`. */
  appendChild(parentId: bigint, childId: bigint): void
  /**
   * Insert `node` immediately before `anchor`. If `anchor` is None, behaves
   * like `appendChild`. Matches `Node.insertBefore`.
   */
  insertBefore(parentId: bigint, nodeId: bigint, anchorId?: bigint | undefined | null): void
  /** Insert `node` immediately after `anchor`. */
  insertAfter(anchorId: bigint, nodeId: bigint): void
  /**
   * Detach a node from its parent. The node is kept around (still
   * addressable by id) so JS wrappers stay valid. Use `drop_node` to
   * release storage.
   */
  remove(nodeId: bigint): void
  /** Detach and free the node. */
  dropNode(nodeId: bigint): void
  /** Replace `anchor` with `node` in its parent. */
  replaceWith(anchorId: bigint, nodeId: bigint): void
  /** Replace this element's inner HTML. */
  setInnerHtml(nodeId: bigint, html: string): void
  /**
   * Serialize this node (including the node itself) to HTML. Mirrors
   * `Element.outerHTML`. Returns None for unknown nodes.
   */
  outerHtml(nodeId: bigint): string | null
  /**
   * Serialize the children of this node to HTML, without the node's own
   * open/close tags. Mirrors `Element.innerHTML`.
   */
  innerHtml(nodeId: bigint): string | null
  /**
   * First element id matching the given local tag name (lowercase),
   * or None if no element matches. Pre-order traversal from the
   * document root.
   */
  findFirstByLocalName(name: string): bigint | null
  /**
   * All element ids matching the given local tag name, in tree order.
   * Mirrors `getElementsByTagName(name)` minus the live-collection
   * semantics — JS gets a snapshot.
   */
  findAllByLocalName(name: string): Array<object>
  /**
   * All element ids matching the given local tag name, scoped to the
   * subtree rooted at `root_id` (exclusive — `root_id` itself is not
   * checked). Pre-order DFS from `root_id`'s children.
   */
  findAllByLocalNameIn(root: NativeNode, name: string): Array<object>
  /**
   * All element ids in the subtree rooted at `root_id` (exclusive),
   * i.e. every descendant element regardless of tag. Backs
   * `element.getElementsByTagName("*")`.
   */
  findAllElementsIn(root: NativeNode): Array<object>
  /**
   * All element ids whose `class` attribute contains `class_name` as
   * one of its whitespace-separated tokens. Document-scoped.
   */
  findAllByClassName(className: string): Array<object>
  /**
   * All element ids whose `class` attribute contains `class_name`,
   * scoped to the subtree rooted at `root_id` (exclusive).
   */
  findAllByClassNameIn(root: NativeNode, className: string): Array<object>
  /**
   * `<html>` element. Uses the `local_name!` macro for a zero-cost
   * atom comparison. Returns None for documents without an `<html>`
   * root (unusual but possible during partial parsing).
   */
  htmlElement(): object | null
  headElement(): object | null
  bodyElement(): object | null
}

export declare class NativeNode {
  nodeType(): number
  parentNode(): object | null
  firstChild(): object | null
  lastChild(): object | null
  nextSibling(): object | null
  previousSibling(): object | null
  childNodes(): Array<object>
  textContent(): string | null
  setTextContent(text: string): void
  tagName(): string | null
  getAttribute(name: string): string | null
  getAttributes(): Array<AttrInit>
  setAttribute(name: string, value: string, namespace?: string | undefined | null): void
  removeAttribute(name: string, namespace?: string | undefined | null): void
  getStyleProperty(name: string): string | null
  setStyleProperty(name: string, value: string): void
  removeStyleProperty(name: string): void
  getStylePropertyNames(): Array<string>
  getStyleAttribute(): string
  appendChild(child: NativeNode): object
  insertBefore(node: NativeNode, anchor?: NativeNode | undefined | null): object
  remove(): void
  replaceWith(node: NativeNode): object
  cloneNode(deep: boolean): object
  setInnerHtml(html: string): void
  innerHtml(): string | null
  outerHtml(): string | null
  querySelector(selector: string): object | null
  querySelectorAll(selector: string): Array<object>
  getBoundingClientRect(): DomRect | null
  get scrollTop(): number
  set scrollTop(value: number)
  get scrollLeft(): number
  set scrollLeft(value: number)
  get scrollHeight(): number
  get scrollWidth(): number
  get clientHeight(): number
  get clientWidth(): number
  /**
   * Move focus to this node. Mirrors `HTMLElement.focus()`.
   * Returns true if focus actually changed.
   */
  focus(): boolean
  /** Remove focus from this node (if focused). Mirrors `HTMLElement.blur()`. */
  blur(): void
}

/**
 * Handle to an open window. Construct via `BlitzApp.openWindow`.
 *
 * Shares a `Rc<RefCell<WindowInner>>` with the `WindowEntry` stored in
 * `BlitzApp`. `close_window` takes the `Arc<dyn Window>` out of the inner
 * cell, which releases the OS window even if this JS handle is still alive.
 */
export declare class NativeWindow {
  /** Whether `closeWindow` has run for this handle. */
  get closed(): boolean
  /**
   * Opaque window identifier. JS uses this to map app-event payloads
   * back to the right `Window` wrapper.
   */
  get windowId(): bigint
  /**
   * Get the raw window handle for this window.
   *
   * The returned `RawWindowHandle` can be passed to `WindowOptions.parentWindow()`
   * to create child windows, or to `rfd` dialogs that need a parent window.
   */
  windowHandle(): WindowHandle
  setTitle(title: string): void
  setSize(width: number, height: number): void
  getSize(): Array<number>
  getResizable(): boolean
  currentMonitor(): MonitorInfo | null
  setMinSize(width: number, height: number): void
  setMaxSize(width: number, height: number): void
  setResizable(value: boolean): void
  setMaximized(value: boolean): void
  setVisible(value: boolean): void
  setTransparent(value: boolean): void
  setBlur(value: boolean): void
  setDecorations(value: boolean): void
  setFullscreenBorderless(monitor: MonitorInfo): void
  setFullscreenExclusive(monitor: MonitorInfo, videoMode: VideoModeInfo): void
  setFullscreenNone(): void
  setEnabledButtons(buttons: Array<string>): void
  setWindowIcon(data: Uint8Array): void
}

export declare class PointerData {
  /** "mouse" | "pen" | "finger" */
  get kind(): string
  /** Pointer id; for mouse / pen this is 1, for finger it's the finger id. */
  get pointerId(): number
  get isPrimary(): boolean
  get pageX(): number
  get pageY(): number
  get clientX(): number
  get clientY(): number
  get screenX(): number
  get screenY(): number
  get button(): number
  get buttons(): number
  get pressure(): number
  get tiltX(): number
  get tiltY(): number
  get twist(): number
  get modsBits(): number
}

/** A fullscreen video mode of a monitor. Wraps winit's `VideoMode`. */
export declare class VideoModeInfo {
  get width(): number
  get height(): number
  get bitDepth(): number | null
  get refreshRateMillihertz(): number | null
}

export declare class WheelData {
  /** "lines" | "pixels" */
  get mode(): string
  get deltaX(): number
  get deltaY(): number
  get pageX(): number
  get pageY(): number
  get clientX(): number
  get clientY(): number
  get buttons(): number
  get modsBits(): number
}

/**
 * Opaque wrapper around a platform-specific raw window handle.
 *
 * Obtained from native objects (e.g. `NativeWindow.windowHandle()`).
 * Pass it to APIs that need a parent window, such as `WindowOptions.parentWindow()`,
 * or to `rfd` dialog calls.
 */
export declare class WindowHandle {

}

/**
 * Options accepted by `BlitzApp.openWindow`. Construct via
 * `WindowOptions.builder()`.
 */
export declare class WindowOptions {
  /** Create a new builder with all fields unset. */
  static builder(): WindowOptions
  title(value: string): this
  size(width: number, height: number): this
  resizable(value: boolean): this
  minSize(width: number, height: number): this
  maxSize(width: number, height: number): this
  maximized(value: boolean): this
  visible(value: boolean): this
  transparent(value: boolean): this
  blur(value: boolean): this
  decorations(value: boolean): this
  /** Set borderless fullscreen on the specified monitor. */
  fullscreenBorderless(monitor: MonitorInfo): this
  /** Set exclusive fullscreen using the specified monitor and video mode. */
  fullscreenExclusive(monitor: MonitorInfo, videoMode: VideoModeInfo): this
  enabledButtons(value: Array<string>): this
  windowIcon(value: Uint8Array): this
  /**
   * Set the parent window for this window.
   *
   * Pass a `RawWindowHandle` obtained from `NativeWindow.windowHandle()`.
   */
  parentWindow(handle: WindowHandle): this
}

/**
 * Result reported back from JS after dispatching an app event. A
 * missing call (handler not installed, or threw) acts as
 * `default_prevented = false`.
 */
export interface AppDispatchResult {
  defaultPrevented: boolean
}

/** Payload handed to the JS-side app-event handler. */
export interface AppEventPayload {
  /** `"close" | "closed"` for now. */
  type: string
  /**
   * Opaque window identifier. JS uses this to look up the
   * matching `Window` wrapper.
   */
  windowId: bigint
  /**
   * Whether the JS `Event` constructed from this payload should be
   * cancelable. Only `close` is cancelable; `closed` is not.
   */
  cancelable: boolean
}

/** Plain attribute pair used by the create/insert APIs. */
export interface AttrInit {
  name: string
  value: string
  namespace?: string
}

/** Options shared by all dialog methods. */
export interface DialogOptions {
  /** Dialog title. */
  title?: string
  /** Starting directory. */
  directory?: string
  /** Starting file name (save dialog) or default name. */
  fileName?: string
  /** Extension filters. */
  filters?: Array<FileFilter>
}

/** Configuration passed to `DocHandle.create`. */
export interface DocHandleConfig {
  uaStylesheets?: Array<string>
  baseHtml?: string
}

export interface DomRect {
  x: number
  y: number
  width: number
  height: number
  top: number
  left: number
  bottom: number
  right: number
}

/** Extension filter entry, e.g. `{ name: "Images", extensions: ["png", "jpg"] }`. */
export interface FileFilter {
  /** Display name shown in the filter dropdown. */
  name: string
  /** File extensions without leading dot, e.g. `["png", "jpg"]`. */
  extensions: Array<string>
}

/**
 * One-time env injection. JS calls this during addon init (before any
 * register_* calls) so that `global::env()` works in callbacks that don't
 * receive an `Env` parameter (e.g. `EventHandler::handle_event`).
 */
export declare function initEnv(): void

/** Open a single-file picker. Returns the chosen path or `null`. */
export declare function pickFile(options?: DialogOptions | undefined | null, parent?: WindowHandle | undefined | null): Promise<string | null>

/** Open a multi-file picker. Returns an array of paths (may be empty). */
export declare function pickFiles(options?: DialogOptions | undefined | null, parent?: WindowHandle | undefined | null): Promise<Array<string>>

/** Open a single-folder picker. Returns the chosen path or `null`. */
export declare function pickFolder(options?: DialogOptions | undefined | null, parent?: WindowHandle | undefined | null): Promise<string | null>

/** Open a multi-folder picker. Returns an array of paths (may be empty). */
export declare function pickFolders(options?: DialogOptions | undefined | null, parent?: WindowHandle | undefined | null): Promise<Array<string>>

/** Result of one `pumpAppEvents` call. */
export interface PumpResult {
  /** The loop is still running. Caller should pump again later. */
  continue: boolean
  /** The loop has exited (e.g. all windows closed). */
  exit: boolean
  /** Exit code, if `exit`. */
  code?: number
}

export declare function registerCancelBubbleGetter(getter: (event: Event) => boolean): void

export declare function registerDefaultPreventedGetter(getter: (event: Event) => boolean): void

export declare function registerDispatchFn(dispatchFn: (target: EventTarget, event: Event) => unknown): void

export declare function registerElementConstructor(namespace: string, tagName: string, constructor: { new (handle: NativeNode, document: object, extra?: InputDataHandle): object }): void

export declare function registerEventFactory(factory: (payload: EventPayload) => Event): void

/** Options for `DocHandle.registerFont`. */
export interface RegisterFontOptions {
  familyName?: string
  weight?: string
  style?: string
  stretch?: string
}

export declare function registerNodeConstructor(nodeType: number, constructor: { new (handle: NativeNode, document: object): object }): void

/** Open a save-file dialog. Returns the chosen path or `null`. */
export declare function saveFile(options?: DialogOptions | undefined | null, parent?: WindowHandle | undefined | null): Promise<string | null>
