// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (process.report && typeof process.report.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./napi-blitz.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-blitz-android-arm64')
        const bindingPackageVersion = require('@ylcc/napi-blitz-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./napi-blitz.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-blitz-android-arm-eabi')
        const bindingPackageVersion = require('@ylcc/napi-blitz-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if ((process.config && process.config.variables && process.config.variables.shlib_suffix === 'dll.a') || (process.config && process.config.variables && process.config.variables.node_target_type === 'shared_library')) {
        try {
        return require('./napi-blitz.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-blitz-win32-x64-gnu')
        const bindingPackageVersion = require('@ylcc/napi-blitz-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./napi-blitz.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-blitz-win32-x64-msvc')
        const bindingPackageVersion = require('@ylcc/napi-blitz-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./napi-blitz.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-blitz-win32-ia32-msvc')
        const bindingPackageVersion = require('@ylcc/napi-blitz-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./napi-blitz.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-blitz-win32-arm64-msvc')
        const bindingPackageVersion = require('@ylcc/napi-blitz-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./napi-blitz.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@ylcc/napi-blitz-darwin-universal')
      const bindingPackageVersion = require('@ylcc/napi-blitz-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./napi-blitz.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-blitz-darwin-x64')
        const bindingPackageVersion = require('@ylcc/napi-blitz-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./napi-blitz.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-blitz-darwin-arm64')
        const bindingPackageVersion = require('@ylcc/napi-blitz-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./napi-blitz.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-blitz-freebsd-x64')
        const bindingPackageVersion = require('@ylcc/napi-blitz-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./napi-blitz.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-blitz-freebsd-arm64')
        const bindingPackageVersion = require('@ylcc/napi-blitz-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./napi-blitz.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-blitz-linux-x64-musl')
          const bindingPackageVersion = require('@ylcc/napi-blitz-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./napi-blitz.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-blitz-linux-x64-gnu')
          const bindingPackageVersion = require('@ylcc/napi-blitz-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./napi-blitz.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-blitz-linux-arm64-musl')
          const bindingPackageVersion = require('@ylcc/napi-blitz-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./napi-blitz.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-blitz-linux-arm64-gnu')
          const bindingPackageVersion = require('@ylcc/napi-blitz-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./napi-blitz.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-blitz-linux-arm-musleabihf')
          const bindingPackageVersion = require('@ylcc/napi-blitz-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./napi-blitz.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-blitz-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@ylcc/napi-blitz-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./napi-blitz.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-blitz-linux-loong64-musl')
          const bindingPackageVersion = require('@ylcc/napi-blitz-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./napi-blitz.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-blitz-linux-loong64-gnu')
          const bindingPackageVersion = require('@ylcc/napi-blitz-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./napi-blitz.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-blitz-linux-riscv64-musl')
          const bindingPackageVersion = require('@ylcc/napi-blitz-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./napi-blitz.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-blitz-linux-riscv64-gnu')
          const bindingPackageVersion = require('@ylcc/napi-blitz-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./napi-blitz.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-blitz-linux-ppc64-gnu')
        const bindingPackageVersion = require('@ylcc/napi-blitz-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./napi-blitz.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-blitz-linux-s390x-gnu')
        const bindingPackageVersion = require('@ylcc/napi-blitz-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./napi-blitz.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-blitz-openharmony-arm64')
        const bindingPackageVersion = require('@ylcc/napi-blitz-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./napi-blitz.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-blitz-openharmony-x64')
        const bindingPackageVersion = require('@ylcc/napi-blitz-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./napi-blitz.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-blitz-openharmony-arm')
        const bindingPackageVersion = require('@ylcc/napi-blitz-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.3.220' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

function createLoadErrorChain(errors) {
  return errors.reduce((previous, current) => {
    let message
    try {
      message =
        current && typeof current.message === 'string'
          ? current.message
          : String(current)
    } catch {
      message = 'Unknown error'
    }
    const error = new Error(message)
    error.cause = previous
    return error
  }, null)
}

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value → native binding preferred, WASI is only a fallback
//   'true'                   → prefer WASI, but retain native as a lazy fallback
//   'error'                  → require WASI without initializing a native fallback
// Treating any non-empty string as truthy (the historical behavior) meant
// NAPI_RS_FORCE_WASI=false, NAPI_RS_FORCE_WASI=0, etc. inadvertently triggered
// the WASI path, causing ENOENT for packages shipped without a .wasi.cjs file.
//
// NAPI_RS_WASI_FLAVOR selects one exact generated flavor and implies strict
// WASI loading. It never crosses into another flavor or falls back to native.
const __napiWasiFlavors = ["wasm32-wasi"]
const __napiWasiFlavor = process.env.NAPI_RS_WASI_FLAVOR
const __napiWasiFlavorRequested =
  typeof __napiWasiFlavor === 'string' && __napiWasiFlavor.length > 0
if (
  __napiWasiFlavorRequested &&
  __napiWasiFlavors.indexOf(__napiWasiFlavor) === -1
) {
  throw new Error(
    'Unsupported WASI flavor "' +
      __napiWasiFlavor +
      '". Available flavors: ' +
      __napiWasiFlavors.join(', '),
  )
}
const forceWasiError = process.env.NAPI_RS_FORCE_WASI === 'error'
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === 'true' ||
  forceWasiError ||
  __napiWasiFlavorRequested

if (!forceWasi) {
  nativeBinding = requireNative()
}

if (!nativeBinding || forceWasi) {
  let wasiBinding = null
  let wasiBindingLoaded = false
  const wasiBindingErrors = []
  const __napiWasiResolveCandidate = (specifier, isPackage, localArtifacts) => {
    try {
      require.resolve(specifier)
    } catch (resolveError) {
      if (!resolveError || resolveError.code !== 'MODULE_NOT_FOUND') {
        throw resolveError
      }
      if (isPackage) {
        try {
          require.resolve(specifier + '/package.json')
        } catch (packageError) {
          if (packageError && packageError.code === 'MODULE_NOT_FOUND') {
            return resolveError
          }
          // An exports restriction proves the package exists even when its
          // package.json is not public. Preserve the root resolution failure.
          throw resolveError
        }
        // The package exists but its main/export target is broken.
        throw resolveError
      }
      return resolveError
    }
    if (localArtifacts) {
      let artifactError = null
      for (let i = 0; i < localArtifacts.length; i++) {
        try {
          require.resolve(localArtifacts[i])
          return null
        } catch (resolveError) {
          if (!resolveError || resolveError.code !== 'MODULE_NOT_FOUND') {
            throw resolveError
          }
          artifactError = resolveError
        }
      }
      return artifactError
    }
    return null
  }
  if (!wasiBindingLoaded && (!__napiWasiFlavorRequested || __napiWasiFlavor === "wasm32-wasi")) {
    let candidateError = null
    let candidateFailed = false
    try {
      candidateError = __napiWasiResolveCandidate('./napi-blitz.wasi.cjs', false, ["./napi-blitz.wasm32-wasi.debug.wasm","./napi-blitz.wasm32-wasi.wasm"])
      candidateFailed = candidateError !== null
      if (!candidateFailed) {
        wasiBinding = require('./napi-blitz.wasi.cjs')
        nativeBinding = wasiBinding
        wasiBindingLoaded = true
      }
    } catch (err) {
      candidateError = err
      candidateFailed = true
    }
    if (candidateFailed) {
      wasiBindingErrors.push(candidateError)
      loadErrors.push(candidateError)
    }
  }
  if (!wasiBindingLoaded && (!__napiWasiFlavorRequested || __napiWasiFlavor === "wasm32-wasi")) {
    let candidateError = null
    let candidateFailed = false
    try {
      candidateError = __napiWasiResolveCandidate('@ylcc/napi-blitz-wasm32-wasi', true, undefined)
      candidateFailed = candidateError !== null
      if (!candidateFailed) {
        if (process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          const bindingPackageVersion = require('@ylcc/napi-blitz-wasm32-wasi/package.json').version
          if (bindingPackageVersion !== '0.3.220') {
            throw new Error(`WASI binding package version mismatch, expected 0.3.220 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
        }
        wasiBinding = require('@ylcc/napi-blitz-wasm32-wasi')
        nativeBinding = wasiBinding
        wasiBindingLoaded = true
      }
    } catch (err) {
      candidateError = err
      candidateFailed = true
    }
    if (candidateFailed) {
      wasiBindingErrors.push(candidateError)
      loadErrors.push(candidateError)
    }
  }
  if (
    !wasiBindingLoaded &&
    forceWasi &&
    !forceWasiError &&
    !__napiWasiFlavorRequested
  ) {
    nativeBinding = requireNative()
  }
  if ((forceWasiError || __napiWasiFlavorRequested) && !wasiBindingLoaded) {
    const error = new Error(
      __napiWasiFlavorRequested
        ? 'WASI binding for flavor "' + __napiWasiFlavor + '" not found'
        : 'WASI binding not found and NAPI_RS_FORCE_WASI is set to error',
    )
    error.cause = createLoadErrorChain(wasiBindingErrors)
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const error = new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
    )
    // assign instead of the `new Error(message, { cause })` options form,
    // which Node < 16.9 silently ignores
    error.cause = createLoadErrorChain(loadErrors)
    throw error
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.NodeTypes = nativeBinding.NodeTypes
module.exports.MonitorInfo = nativeBinding.MonitorInfo
module.exports.VideoModeInfo = nativeBinding.VideoModeInfo
module.exports.WindowHandle = nativeBinding.WindowHandle
module.exports.WindowOptions = nativeBinding.WindowOptions
module.exports.createDocument = nativeBinding.createDocument
module.exports.defineHtmlBodyEventAttributes = nativeBinding.defineHtmlBodyEventAttributes
module.exports.defineNodeOnEventAttributes = nativeBinding.defineNodeOnEventAttributes
module.exports.defineWindowEventAttributes = nativeBinding.defineWindowEventAttributes
module.exports.pickFile = nativeBinding.pickFile
module.exports.pickFiles = nativeBinding.pickFiles
module.exports.pickFolder = nativeBinding.pickFolder
module.exports.pickFolders = nativeBinding.pickFolders
module.exports.saveFile = nativeBinding.saveFile
module.exports.setListenerOps = nativeBinding.setListenerOps
module.exports.setPumpAppLoop = nativeBinding.setPumpAppLoop
module.exports.AttributesHandlerClass = nativeBinding.AttributesHandlerClass
module.exports.BlitzAppClass = nativeBinding.BlitzAppClass
module.exports.CharacterDataClass = nativeBinding.CharacterDataClass
module.exports.CommentClass = nativeBinding.CommentClass
module.exports.CompositionEventClass = nativeBinding.CompositionEventClass
module.exports.CustomEventClass = nativeBinding.CustomEventClass
module.exports.DocumentClass = nativeBinding.DocumentClass
module.exports.ElementClass = nativeBinding.ElementClass
module.exports.EventClass = nativeBinding.EventClass
module.exports.EventTargetClass = nativeBinding.EventTargetClass
module.exports.FocusEventClass = nativeBinding.FocusEventClass
module.exports.FontFaceClass = nativeBinding.FontFaceClass
module.exports.FontFaceSetClass = nativeBinding.FontFaceSetClass
module.exports.HTMLBodyElementClass = nativeBinding.HTMLBodyElementClass
module.exports.HTMLDocumentClass = nativeBinding.HTMLDocumentClass
module.exports.HTMLElementClass = nativeBinding.HTMLElementClass
module.exports.HTMLHtmlElementClass = nativeBinding.HTMLHtmlElementClass
module.exports.HTMLInputElementClass = nativeBinding.HTMLInputElementClass
module.exports.HTMLTextAreaElementClass = nativeBinding.HTMLTextAreaElementClass
module.exports.InputEventClass = nativeBinding.InputEventClass
module.exports.KeyboardEventClass = nativeBinding.KeyboardEventClass
module.exports.MessageEventClass = nativeBinding.MessageEventClass
module.exports.MouseEventClass = nativeBinding.MouseEventClass
module.exports.NodeClass = nativeBinding.NodeClass
module.exports.PointerEventClass = nativeBinding.PointerEventClass
module.exports.StyleHandlerClass = nativeBinding.StyleHandlerClass
module.exports.TextClass = nativeBinding.TextClass
module.exports.UIEventClass = nativeBinding.UIEventClass
module.exports.WheelEventClass = nativeBinding.WheelEventClass
module.exports.WindowClass = nativeBinding.WindowClass
module.exports.AttributesHandler = nativeBinding.AttributesHandler
module.exports.BlitzApp = nativeBinding.BlitzApp
module.exports.CharacterData = nativeBinding.CharacterData
module.exports.Comment = nativeBinding.Comment
module.exports.CompositionEvent = nativeBinding.CompositionEvent
module.exports.CustomEvent = nativeBinding.CustomEvent
module.exports.Document = nativeBinding.Document
module.exports.Element = nativeBinding.Element
module.exports.Event = nativeBinding.Event
module.exports.EventTarget = nativeBinding.EventTarget
module.exports.FocusEvent = nativeBinding.FocusEvent
module.exports.FontFace = nativeBinding.FontFace
module.exports.FontFaceSet = nativeBinding.FontFaceSet
module.exports.HTMLBodyElement = nativeBinding.HTMLBodyElement
module.exports.HTMLDocument = nativeBinding.HTMLDocument
module.exports.HTMLElement = nativeBinding.HTMLElement
module.exports.HTMLHtmlElement = nativeBinding.HTMLHtmlElement
module.exports.HTMLInputElement = nativeBinding.HTMLInputElement
module.exports.HTMLTextAreaElement = nativeBinding.HTMLTextAreaElement
module.exports.InputEvent = nativeBinding.InputEvent
module.exports.KeyboardEvent = nativeBinding.KeyboardEvent
module.exports.MessageEvent = nativeBinding.MessageEvent
module.exports.MouseEvent = nativeBinding.MouseEvent
module.exports.Node = nativeBinding.Node
module.exports.PointerEvent = nativeBinding.PointerEvent
module.exports.StyleHandler = nativeBinding.StyleHandler
module.exports.Text = nativeBinding.Text
module.exports.UIEvent = nativeBinding.UIEvent
module.exports.WheelEvent = nativeBinding.WheelEvent
module.exports.Window = nativeBinding.Window
