/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BlitzApp {
  /** Build the winit event loop and underlying blitz application. */
  static create(): BlitzApp
  /**
   * Install (or replace) the JS callback that receives app/window
   * events. JS wires this in its `BlitzApp` constructor; calling
   * again replaces the previous handler.
   *
   * The callback receives an `AppEventPayload` and must return an
   * `AppDispatchResult` reporting whether the JS-side `Event` had
   * `preventDefault()` called on it.
   */
  setAppEventHandler(callback: (arg: AppEventPayload) => AppDispatchResult): void
  /**
   * Attach a new window to the given document handle. The same handle can
   * only be attached to one window. The JS DocHandle keeps working after
   * this call (it shares state with the window via Rc<RefCell<...>>), so
   * JS can keep mutating the DOM after `openWindow`.
   *
   * `options` maps directly to a winit `WindowAttributes`. If the document
   * carries a `<title>` element, blitz's mutator-flush will overwrite the
   * title shortly after open; this is expected, with the document treated
   * as the source of truth for window-title content.
   *
   * The returned `Window` carries the `doc_id` of the attached document,
   * which we use as the napi-side window identifier. Note that winit's
   * real `WindowId` is only minted on the next `pump_app_events` call,
   * so the doc_id is what we key on for synchronous open/close.
   */
  openWindow(doc: DocHandle, options?: WindowOptions | undefined | null): Window
  /**
   * Synchronously close the given window. Removes it from the
   * application's window map (or from our pending queue if it has not
   * been initialised yet). The window stops painting and receiving
   * events as soon as this call returns.
   *
   * This is intentionally not GC-driven: dropping the JS `Window` object
   * does not close the OS window. Callers must invoke this explicitly.
   */
  closeWindow(window: Window): void
  /**
   * winit `Window::request_surface_size`. The actual size that the
   * platform settles on can differ from the request; callers should
   * rely on the `surface-resize` events (driven by winit) to reflect
   * the truth.
   *
   * The JS-facing boundary intentionally accepts `f64`, matching JS
   * `number`, instead of `u32`: napi's unsigned integer conversion would
   * silently apply ToUint32 semantics to negatives/fractions. We validate
   * the double ourselves and only then pass a `PhysicalSize<u32>` to winit.
   */
  setWindowInnerSize(window: Window, width: number, height: number): void
  /**
   * winit `Window::surface_size`. Returns `[width, height]` in
   * physical pixels, or `None` if the window has not been created
   * yet or has been closed.
   */
  getWindowInnerSize(window: Window): Array<number> | null
  /** winit `Window::set_resizable`. */
  setWindowResizable(window: Window, resizable: boolean): void
  /**
   * winit `Window::is_resizable`. Returns `None` if the window has
   * not been created yet or has been closed.
   */
  getWindowResizable(window: Window): boolean | null
  /**
   * Pump pending winit events for at most `millis` milliseconds. JS should
   * call this in a loop (typically once per animation frame) to drive the
   * renderer and event handling.
   */
  pumpAppEvents(millis: number): PumpResult
}

/**
 * JS-facing handle. Holds the shared document state and exposes the flat
 * nodeId-based DOM API.
 */
export declare class DocHandle {
  /** Create a new document. */
  static create(config: DocHandleConfig): DocHandle
  /**
   * Recompute style + layout. Called from JS after batches of mutations or
   * before painting. `time_ms` drives CSS animations.
   */
  resolve(timeMs: number): void
  /**
   * Register a font from a raw byte buffer.
   *
   * The buffer must contain a single TTF/OTF/WOFF/WOFF2 font file (or
   * a TrueType collection — every face inside will be registered).
   * Returns the number of faces that were added.
   *
   * This bypasses blitz's `@font-face` machinery entirely: there is
   * no network fetch, no CSS parsing, just a direct insert into the
   * shared `Collection`. The font becomes available to all subsequent
   * layout/paint work driven by this document.
   *
   * The buffer is taken by value and stored inside the font cache;
   * callers may safely drop their reference to it after this call
   * returns.
   */
  registerFont(data: Uint8Array, options?: RegisterFontOptions | undefined | null): number
  /** The id of the root node (always 0 for blitz, but expose it for JS). */
  rootNodeId(): bigint
  /** The id of `<html>` (the root *element*). */
  rootElementId(): bigint
  /**
   * Update the set of node ids JS currently has live wrappers for. Rust
   * uses this to short-circuit dispatch when no listener could exist.
   */
  setListenedNodes(ids: Array<bigint>): void
  /**
   * Add a single node id to the listened set. Cheaper than calling
   * `set_listened_nodes` for incremental subscription updates.
   */
  addListenedNode(id: bigint): void
  /** Remove a node id from the listened set. */
  removeListenedNode(id: bigint): void
  /**
   * Replace document content from an HTML string. Useful for tests and
   * initial bootstrapping when `base_html` was not enough.
   */
  loadHtml(html: string): void
  /** Find a single node by CSS selector. Returns its node id or null. */
  querySelector(selector: string): bigint | null
  /** Find all nodes by CSS selector. Returns a list of node ids. */
  querySelectorAll(selector: string): Array<bigint>
  /**
   * Element-scoped `querySelector`: first match in the subtree rooted at
   * `root_id` (exclusive — the root element itself is not a candidate,
   * matching the DOM spec for `Element.querySelector`). We parse the
   * selector via blitz's public `try_parse_selector_list` and then call
   * stylo's `dom_apis::query_selector` directly with `root_id`'s node as
   * the root — bypassing blitz's `query_selector_raw`, which is hardcoded
   * to `self.root_node()`.
   */
  querySelectorIn(rootId: bigint, selector: string): bigint | null
  /**
   * Element-scoped `querySelectorAll`: all matches in the subtree rooted
   * at `root_id` (exclusive). Same approach as `query_selector_in`.
   */
  querySelectorAllIn(rootId: bigint, selector: string): Array<bigint>
  /** Lookup by `id=` attribute, like `document.getElementById`. */
  getElementById(id: string): bigint | null
  /**
   * Find the document's `<title>` element id, or None if no title
   * element exists in the tree. Uses the same pre-order DFS as the
   * other structural lookups (`html`/`head`/`body`) — cheaper than
   * `querySelector("title")` which dispatches through the CSS
   * selector engine.
   */
  findTitleNodeId(): bigint | null
  /** True iff the given node id currently exists in the document. */
  hasNode(id: bigint): boolean
  /**
   * Create an element node. Returns its node id. The element is detached
   * (no parent) until inserted.
   */
  createElement(localName: string, namespace?: string | undefined | null, attrs?: Array<AttrInit> | undefined | null): bigint
  /** Create a text node with the given content. */
  createTextNode(text: string): bigint
  /** Create an empty comment node. */
  createCommentNode(): bigint
  /** Deep-clone an existing node and return the new node's id. */
  deepCloneNode(nodeId: bigint): bigint
  /**
   * Shallow-clone a node: same data (tag name, attributes, text
   * payload, etc.) but no children. The new node has no parent.
   * Returns the new node's id.
   *
   * Cloning a missing nodeId returns 0 (the document root) — the
   * caller should make sure the source id is valid first. The
   * alternative (returning `Option<u64>`) noisily complicates the
   * JS-side cloneNode wrapper for a case JS code can never trigger.
   */
  shallowCloneNode(nodeId: bigint): bigint
  /** Parent node id, if any. */
  parentId(nodeId: bigint): bigint | null
  /** First child id, if any. */
  firstChildId(nodeId: bigint): bigint | null
  /** Last child id, if any. */
  lastChildId(nodeId: bigint): bigint | null
  /** All children, in document order. */
  childIds(nodeId: bigint): Array<bigint>
  /** Next sibling id, if any. */
  nextSiblingId(nodeId: bigint): bigint | null
  /** Previous sibling id, if any. */
  previousSiblingId(nodeId: bigint): bigint | null
  /** DOM-style `nodeType` (1=Element, 3=Text, 8=Comment, 9=Document). */
  nodeType(nodeId: bigint): number
  /**
   * Local element tag name (lowercased), e.g. "div". Returns None for
   * non-element nodes.
   */
  tagName(nodeId: bigint): string | null
  /**
   * Concatenated text content of this node and its descendants. Mirrors
   * `Node.textContent`.
   */
  textContent(nodeId: bigint): string | null
  /** Get an attribute value, or None if missing or node is not an element. */
  getAttribute(nodeId: bigint, name: string): string | null
  /**
   * All attribute (name, value) pairs on this node, or empty if not an
   * element.
   */
  getAttributes(nodeId: bigint): Array<AttrInit>
  /** Set an attribute on an element. */
  setAttribute(nodeId: bigint, name: string, value: string, namespace?: string | undefined | null): void
  /** Remove an attribute from an element. */
  removeAttribute(nodeId: bigint, name: string, namespace?: string | undefined | null): void
  /** Set a single inline style property (e.g. "color", "#ff0000"). */
  setStyleProperty(nodeId: bigint, name: string, value: string): void
  /** Remove a single inline style property. */
  removeStyleProperty(nodeId: bigint, name: string): void
  /**
   * Read a single inline style property's serialized value, or
   * `null` if the property is not set on this element.
   *
   * Implements CSSOM `CSSStyleDeclaration.getPropertyValue`:
   * the value is rendered through stylo's `property_value_to_css`,
   * which handles both longhands and shorthands. An unknown
   * property name (one stylo doesn't recognize) also returns `null`
   * rather than throwing — matching browser semantics.
   */
  getStyleProperty(nodeId: bigint, name: string): string | null
  /**
   * List the long-hand names of every property currently in this
   * element's inline style block.
   *
   * Used by the JS-side `style` Proxy to implement `Object.keys`,
   * `for...in`, and `length`. The names are stylo's longhand
   * identifiers (e.g. `"color"`, `"margin-top"`). Custom properties
   * (`--foo`) are included as-is.
   */
  getStylePropertyNames(nodeId: bigint): Array<string>
  /**
   * Read the entire `style` attribute as a single CSS string. Used
   * to back `CSSStyleDeclaration.cssText`. Returns the empty string
   * when the element has no inline style at all.
   */
  getStyleAttribute(nodeId: bigint): string
  /**
   * Replace this node's text content. For elements this resets to a single
   * text-node child; for text/comment nodes this updates their content.
   */
  setTextContent(nodeId: bigint, text: string): void
  /** Append `child` as the last child of `parent`. Mirrors `Node.appendChild`. */
  appendChild(parentId: bigint, childId: bigint): void
  /**
   * Insert `node` immediately before `anchor`. If `anchor` is None, behaves
   * like `appendChild`. Matches `Node.insertBefore`.
   */
  insertBefore(parentId: bigint, nodeId: bigint, anchorId?: bigint | undefined | null): void
  /** Insert `node` immediately after `anchor`. */
  insertAfter(anchorId: bigint, nodeId: bigint): void
  /**
   * Detach a node from its parent. The node is kept around (still
   * addressable by id) so JS wrappers stay valid. Use `drop_node` to
   * release storage.
   */
  remove(nodeId: bigint): void
  /** Detach and free the node. */
  dropNode(nodeId: bigint): void
  /** Replace `anchor` with `node` in its parent. */
  replaceWith(anchorId: bigint, nodeId: bigint): void
  /** Replace this element's inner HTML. */
  setInnerHtml(nodeId: bigint, html: string): void
  /**
   * Serialize this node (including the node itself) to HTML. Mirrors
   * `Element.outerHTML`. Returns None for unknown nodes.
   */
  outerHtml(nodeId: bigint): string | null
  /**
   * Serialize the children of this node to HTML, without the node's own
   * open/close tags. Mirrors `Element.innerHTML`.
   */
  innerHtml(nodeId: bigint): string | null
  /**
   * First element id matching the given local tag name (lowercase),
   * or None if no element matches. Pre-order traversal from the
   * document root.
   */
  findFirstByLocalName(name: string): bigint | null
  /**
   * All element ids matching the given local tag name, in tree order.
   * Mirrors `getElementsByTagName(name)` minus the live-collection
   * semantics — JS gets a snapshot.
   */
  findAllByLocalName(name: string): Array<bigint>
  /**
   * All element ids matching the given local tag name, scoped to the
   * subtree rooted at `root_id` (exclusive — `root_id` itself is not
   * checked). Pre-order DFS from `root_id`'s children.
   */
  findAllByLocalNameIn(rootId: bigint, name: string): Array<bigint>
  /**
   * All element ids in the subtree rooted at `root_id` (exclusive),
   * i.e. every descendant element regardless of tag. Backs
   * `element.getElementsByTagName("*")`.
   */
  findAllElementsIn(rootId: bigint): Array<bigint>
  /**
   * All element ids whose `class` attribute contains `class_name` as
   * one of its whitespace-separated tokens. Document-scoped.
   */
  findAllByClassName(className: string): Array<bigint>
  /**
   * All element ids whose `class` attribute contains `class_name`,
   * scoped to the subtree rooted at `root_id` (exclusive).
   */
  findAllByClassNameIn(rootId: bigint, className: string): Array<bigint>
  /**
   * `<html>` element id. Uses the `local_name!` macro for a zero-cost
   * atom comparison. Returns None for documents without an `<html>`
   * root (unusual but possible during partial parsing).
   */
  htmlElementId(): bigint | null
  /** `<head>` element id, or None if missing. */
  headElementId(): bigint | null
  /** `<body>` element id, or None if missing. */
  bodyElementId(): bigint | null
}

/** Handle to an open window. Construct via `BlitzApp.openWindow`. */
export declare class Window {
  /** Whether `closeWindow` has run for this handle. */
  get closed(): boolean
  /**
   * Internal blitz `BaseDocument` id of the attached document. JS
   * uses this to map app-event payloads back to the right `Window`
   * wrapper. Stable for the lifetime of the window.
   */
  get docId(): bigint
}

/**
 * Result reported back from JS after dispatching an app event. A
 * missing call (handler not installed, or threw) acts as
 * `default_prevented = false`.
 */
export interface AppDispatchResult {
  defaultPrevented: boolean
}

/**
 * Payload handed to the JS-side app-event handler. One shape for all
 * of our app/window events; fields not relevant to a given event are
 * left at their defaults.
 */
export interface AppEventPayload {
  /** `"close" | "closed"` for now. */
  eventType: string
  /**
   * `BaseDocument::id` of the window the event refers to. JS uses
   * this to map back to the right `Window` wrapper.
   */
  windowDocId: bigint
  /**
   * Whether the JS `Event` constructed from this payload should be
   * cancelable. Only `close` is cancelable; `closed` is not.
   */
  cancelable: boolean
}

/** Plain attribute pair used by the create/insert APIs. */
export interface AttrInit {
  name: string
  value: string
  namespace?: string
}

/** JS reports back per-event how dispatch went. */
export interface DispatchResult {
  /** JS called `event.preventDefault()` somewhere. */
  defaultPrevented: boolean
  /**
   * JS called `event.stopPropagation()` somewhere. We don't need this on the
   * Rust side semantically (JS already stopped its own bubble), but we still
   * surface it so blitz can skip its default action when appropriate.
   */
  propagationStopped: boolean
  /** JS wants a redraw; usually because a listener mutated the DOM. */
  requestRedraw: boolean
}

/** Configuration passed to `DocHandle.create`. */
export interface DocHandleConfig {
  /** Optional UA stylesheets. Defaults to blitz's DEFAULT_CSS. */
  uaStylesheets?: Array<string>
  /** Optional initial HTML. Defaults to a blank document. */
  baseHtml?: string
  /**
   * Required: a JS callback `(payload: EventPayload) => DispatchResult` that
   * the Rust side calls every time blitz produces a DomEvent. The JS layer
   * uses it to drive its own `EventTarget` chain.
   */
  onDispatch: (arg: EventPayload) => DispatchResult
}

/**
 * One DomEvent serialized for JS consumption.
 *
 * `chain` lists node ids from the event target (index 0) up to the root.
 * JS uses this to run capture (root -> target) followed by bubble
 * (target -> root) using a standard `EventTarget` for each node.
 */
export interface EventPayload {
  /** Event name in DOM-spec lowercased form, e.g. "click", "pointerdown". */
  eventType: string
  /** node id of the original event target. */
  target: bigint
  /** node id chain, target first, root last. */
  chain: Array<bigint>
  /** `event.bubbles` */
  bubbles: boolean
  /** `event.cancelable` */
  cancelable: boolean
  /** Pointer/mouse details, when applicable. */
  pointer?: PointerData
  /** Wheel delta, when applicable. */
  wheel?: WheelData
  /** Keyboard details, when applicable. */
  key?: KeyData
  /** `<input>` value carried by `Input` events. */
  input?: InputData
  /** IME details, when applicable. */
  ime?: ImeData
}

export interface ImeData {
  /** "enabled" | "disabled" | "preedit" | "commit" | "deleteSurrounding" */
  kind: string
  text?: string
  cursorStart?: number
  cursorEnd?: number
  beforeBytes?: number
  afterBytes?: number
}

export interface InputData {
  value: string
}

export interface KeyData {
  /** e.g. "a", "ArrowLeft", "Enter" */
  key: string
  /** e.g. "KeyA", "ArrowLeft", "Enter" */
  code: string
  location: number
  modsBits: number
  repeat: boolean
  isComposing: boolean
  /** "pressed" | "released" */
  state: string
  text?: string
}

export interface PointerData {
  /** "mouse" | "pen" | "finger" */
  kind: string
  /** Pointer id; for mouse / pen this is 1, for finger it's the finger id. */
  pointerId: number
  isPrimary: boolean
  pageX: number
  pageY: number
  clientX: number
  clientY: number
  screenX: number
  screenY: number
  button: number
  buttons: number
  pressure: number
  tiltX: number
  tiltY: number
  twist: number
  modsBits: number
}

/** Result of one `pumpAppEvents` call. */
export interface PumpResult {
  /** The loop is still running. Caller should pump again later. */
  continue: boolean
  /** The loop has exited (e.g. all windows closed). */
  exit: boolean
  /** Exit code, if `exit`. */
  code?: number
}

/**
 * Options for `DocHandle.registerFont`. All fields are optional and act
 * as overrides for the metadata that `parley` would otherwise read from
 * the font file's own tables.
 *
 * Mirrors the subset of CSS `@font-face` descriptors that map cleanly
 * onto the underlying font cache. Each `weight` / `style` / `stretch`
 * value is a CSS string (e.g. `"400"`, `"bold"`, `"italic"`,
 * `"oblique 14deg"`, `"condensed"`, `"75%"`); invalid input is
 * reported back to JS as a thrown error, matching how the browser
 * rejects invalid `FontFaceDescriptors`.
 */
export interface RegisterFontOptions {
  /**
   * Override the family name reported to CSS. If omitted, the family
   * name embedded in the font file is used.
   */
  familyName?: string
  /**
   * CSS `font-weight` descriptor string, e.g. `"400"`, `"bold"`,
   * `"100 900"` (variable). For variable fonts the lower bound is
   * used as the registered weight.
   */
  weight?: string
  /**
   * CSS `font-style` descriptor, e.g. `"normal"`, `"italic"`,
   * `"oblique"`, `"oblique 14deg"`.
   */
  style?: string
  /**
   * CSS `font-stretch` descriptor, e.g. `"normal"`, `"condensed"`,
   * `"75%"`. (Standard name; we keep the CSS spelling rather than
   * fontique's `width`.)
   */
  stretch?: string
}

export interface WheelData {
  /** "lines" | "pixels" */
  mode: string
  deltaX: number
  deltaY: number
  pageX: number
  pageY: number
  clientX: number
  clientY: number
  buttons: number
  modsBits: number
}

/**
 * Options accepted by `BlitzApp.openWindow`. All fields are optional and
 * map directly to winit `WindowAttributes` (0.31). Naming follows winit
 * where it diverges from web (e.g. `surface_size` rather than
 * `inner_size` — winit 0.31 renamed inner -> surface).
 */
export interface WindowOptions {
  /**
   * Initial window title. May be transient: if the document carries a
   * `<title>` element, blitz will overwrite the title on the next
   * mutator flush. Without a `<title>` element this title persists.
   */
  title?: string
  /**
   * Initial surface width in physical pixels.
   *
   * JS `number` values arrive as doubles. Keep this as `f64` at the
   * N-API boundary so we can explicitly reject negatives, fractions,
   * NaN, and Infinity before converting to winit's `u32` size type.
   */
  width?: number
  /**
   * Initial surface height in physical pixels. See `width` for why the
   * boundary type is `f64` rather than `u32`.
   */
  height?: number
  /**
   * Whether the window is initially resizable. Defaults to winit's
   * platform default (typically `true`).
   */
  resizable?: boolean
}
