[package]
name = "napi-inherit-proc"
version = "0.2.219"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
napi-derive-backend = { version = "6.1.2", features = ["type-def"] }

[dependencies.proc-macro2]
version = "1"

[dependencies.quote]
version = "1"

[dependencies.syn]
version = "2"
features = [
    "fold",
    "full",
    "extra-traits",
]
