/* eslint-disable */

type ClassType<T extends abstract new (...args: any) => any> =
  & { new(...args: ConstructorParameters<T>): InstanceType<T> }
  & { [K in keyof T]: T[K] };

/* auto-generated by NAPI-RS */

